repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
{%- if cookiecutter.use_black %}
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
{%- endif %}
