repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
{%- if cookiecutter.use_ruff %}
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --exit-zero ]
      verbose: true
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
{%- endif %}
