name: Run Pytest

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python {{ "${{" }} matrix.python-version {{ "}}" }}
      uses: actions/setup-python@v5
      with:
        python-version: {{ "${{" }} matrix.python-version {{ "}}" }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest

    - name: Test with pytest
      run: |
        pytest -v
